### PR TITLE
Add test data

### PR DESCRIPTION
**Pull request by martinez-guillaume**

### CODE REVIEW

**Comment by fodil-a** [comment]
Can you use the profiles, so that it's run only when we use a specific profile, like "dev"
You can do that by following [this](https://www.baeldung.com/spring-profiles)
You have to create the profile in pom.xml (see section 4.6) and basically just add `@Profile("dev")` in the class you created.

And if you want to do even better, try to have real names/information.
To do that, you have to use [this](https://github.com/DiUS/java-faker)

**Review by fodil-a — CHANGES_REQUESTED** [review]
Can you use the profiles, so that it's run only when we use a specific profile, like "dev"
You can do that by following [this](https://www.baeldung.com/spring-profiles)
You have to create the profile in pom.xml (see section 4.6) and basically just add `@Profile("dev")` in the class you created.

And if you want to do even better, try to have real names/information.
To do that, you have to use [this](https://github.com/DiUS/java-faker)

This is going to be fun !!

**Comment by martinez-guillaume** [comment]
it was super interesting , thanks

**Review by fodil-a — APPROVED** [review]
LGTM!

**Pull request merged**
